### ISSUE TITLE
e4159ea5-4e24-4fae-ae41-a3f35f8b97f9.md

### ISSUE THREAD

**Issue by weva86** [SumoLogic/cloud-siem-content-catalog#13]
Windows - Microsoft-Windows-Sysmon/Operational - 7
So where is the imageloaded fields here?

**Comment by jc-sumo** [comment]
It is mapped to `baseImage`

## Input Requirements

|Input|Value|
|-----|-----|
|Vendor|Microsoft|
|Product|Windows|
|Log Format|Windows|
|Event ID Regex Pattern|`Microsoft-Windows-Sysmon/Operational-7`|

## Record Output

|Output|Value|
|------|-----|
|Vendor|Microsoft|
|Product|Windows|
|Record Type|Endpoint|

## Fields Mapped

|CSE Schema Field|Original Record Key|Notes|
|----------------|-------------------|-----|
|baseImage|EventData.ImageLoaded||
|description|None|The static text `Sysmon observed image load` is populated in this schema field.|
|device_hostname|Computer||
|file_hash_imphash|IMPHASH||
|file_hash_md5|MD5||
|file_hash_sha1|SHA1||
|file_hash_sha256|SHA256||
|parentBaseImage|EventData.Image||
|sourceUid|EventRecordID||
|timestamp|EventData.UtcTime|We expect the orginal record value of `EventData.UtcTime` is in the format `yyyy-MM-dd HH:mm:ss.SSS`|
|user_userId|Security.UserID||
